### ISSUE TITLE
Song popup shows the last played Song on playback change

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#10]
It does not happen always, but fairly regularly
![image](https://user-images.githubusercontent.com/13354331/32416988-891c94b8-c252-11e7-975c-d4576d90aa72.png)
a new song plays, and that display thingy shows all the information about the previously played track

**Comment by sghpjuikit** [comment]
I'm aware of the issue. I'll look into it.

**Comment by sghpjuikit** [comment]
Fixed.

The problem was nasty - FileInfo widget uses event reducer to throttle updating in fast event successions (this makes sense, when the widget is observing source such as playlist table selection), but in case of playback change, there are actually 2 events fired, one for the change in currently playing song and one for content refresh of the old one (on playback change, the tag of the previous song is written to and the application fires a refresh to all components that display information about it). Unfortunately, the refresh may fire later (because this is also throttled and consequently delayed).

Normally, this is not a problem, because FileInfo only reacts on content refresh if its content matches the song that is being refreshed (the old one), but because it delays setting new content after playback is changed due to throttling, the ifContentMatches() check still evaluates to true and thus sets up reading of the old song data, unfortunately, by passing it into the event throttler where it basically overwrites the playback change event...
So basically the refresh should not happen, because the application fires it after playback change (so content should be different, thus no refresh), but the widget queues the events, which causes the old content to stick around for longer, which causes the refresh to activate anyway and because it uses the event throttler too, it inadvertently discards the previous event if the time difference is small or simply overwrites the content later if not.

The solution is either to not queue refreshes up (in FileInfo) or only queue them if the queue is empty. The first solution is in theory prone to performance degradation, but in reality will never happen, because the refresh events are already throttled to begin with. It does however involve unnecessarily reacting on two events on each playback change. The second solution is cleaner, also because it does not depend on external implementation, but introduces state checking. I used 2nd solution, because it decouples the implementations and avoids explaining all this in the code to the innocent developer, who may wonder why the refresh events are not queued as the rest, thus reduces cognitive complexity. The state checking has also been refactored out by introducing EventReducer#hasQueuedEvents() method so it came down to adding a simple if check.

This bug has been bugging me for a long time and eluding my attempts to find the cause. It seems that even the simplest uses of reactive programming have their drawbacks, which only further hints at the importance of the simplicity of both the design and the implementation.
