### ISSUE TITLE
Recursive file watching on non-Windows

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#101]

**Comment by sghpjuikit** [comment]
Implementing this using recursive FileWatchers and Subscribtion/Disposert pattern may be relatively easy, but we are still risking leaks and misbehavior due to relying on unpredictable low level behavior. The Java monitors are known for skipping events and such. There could be a better solution out there that someone already created. I'm a little too busy for this, but I'll have a look.

**Comment by sghpjuikit** [comment]
Mentioned in other issue (#103 ): https://stackoverflow.com/questions/8699293/how-to-monitor-a-complete-directory-tree-for-changes-in-linux

This "problem" will need to be taken care of, but I just do not have it in me to dive into Linux implementation specifics and investigations of Java libraries that attempt to solve this. I'm putting this on hold for the time being.

**Comment by sghpjuikit** [comment]
Implemented in 25f2e59.

Implemented using recursive watchers with modify event throttling (100ms) and consequent CREATE->MODIFY->DELETE order guarantee. I was also inspired by existing solutions.

Seems to work as desired, but there may be event skipping and other issues to to threading and potential Java watcher implementation issues. Finding out would require extensive testing effort. Does sufficient job for our use case. If problems arise this may be opened again and tackled with a library.
