### ISSUE TITLE
Improve layout editing

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#104]
When clicking on an empty space, you see 4 options, but "Widget", the most important, is displayed in the same size as all the others. It should be emphasized and the other ones less prominently displayed.

Also, we should add templates, which are simply predefined arrangements of Widgets, so users can get started more quickly without bothering with the nitty-gritty arranging of stuff.

**Comment by sghpjuikit** [comment]
Widget picking and layouting UX is not easy to get right and also blocked by porting to Kotlin. I will think about what can be done in this regard, but we are dealing with several not so major enhancements instead of single issue. On top of that, its difficult to objectively define the exact goal of this task.

The template feature is already there. It is possible export widget or container, i.e., any part of the layout to a file and then load it - it restores complete widget/layout state. This is however not intuitive to use and needs more work. It needs to be more transparent and obvious.

I agree we need more templates and some default ones as well.

**Comment by sghpjuikit** [comment]
I have recently fixed/improved
- split container inefficiencies
- free form container (altogether, had major issues)
- component area controls (more lazy, less icons, wrong icon states)

As for the suggested changes:
- I'm not sure the widget option is more relevant or that it should be highlighted. This is really a design choice/problem. Changing this requires lots of effort and may not end up helping at all. The way to do would be to introduce skinning support for the picker control. This is fully doable at this point, but way down on the priority list and it entails adding similar support for more than just this one part. I'll keep this in mind, but for now it is **considered not an issue**.
- templates are there, component exporting/importing is fully supported and implemented. What is missing is some kind of starter layout. Except there actually is one in the 1st page of the guide, but it is probably easy to skip. Continues in #143
