### ISSUE TITLE
Add icons to widgets

### ISSUE THREAD

**Issue by xerus2000** [sghpjuikit/player#113]
Choosing a widget from this large grid is annoying, since there is no way to immediately identify one. Each should have an icon to clearly distinct them.

**Comment by sghpjuikit** [comment]
I must admit finding the correct widget is a nightmare. I have made some UI improvements to the widget grid, so please have a look.

Workaround:
Although one can do: CTRL+SHIFT+I > "widget name" > "Open widget 'widget name'". This is very quick and I usually use this instead of the widget grid. One can easily move the widget from layout to layout if the just opened widget is desired to be used elsewhere.
I dont know how I would communicate this usage to user.

Icons:
Yes, we could add icons to the widgets. This is sort of meta, i.e., belongs to the WidgetFactory, not Widget and as such should be static information in the Controller of the widget. Fortunately we can use companion objects for Widgets in Kotlin. Unfortunately, Java has no such concept.

I would say this is blocked by creating this entire widgetFactory scope mechanism. Which would also be used instead of the dreaded Widget.Info annotation. Due to some widgets being in Java, this is more complicated (both mechanisms would need to be supported). As for why not just use the annotation for now: well, we can, but its pushing it, and icons can not even be put into the annotation - only their String id, which is not type safe.

I will investigate the situation (not many Java widgets remain) and see which path to take.

Some questions:
- do we want to even support Java-based widgets?
 - They do not support configurable properties, which complicates their lifecycle (init() and refresh)() methods) and makes them hard to code.
 - They also do not have companions (which is gonna be an issue). I think supporting them but in a limited scope is the best case scenario.
- How do we display the icon in the grid? Is it going to be font sized icon left of the text or a big icon in the center with the text bottom of it?

**Comment by Xerus2000** [comment]
We should not put any resources towards Java-based widgets. Instead, gradually port them over to Kotlin and when all are ported remove support for Java-widgets. I don't see why you would ever write a widget in Java again.
Yes, there should be default icons (one for a standard widget and one for a composite widget), it should not be required that each Widget have an icon.

We could even solve this whole thing without any changes in the Widgets code: Just define that the icon filename is "icon._ext_" and is in the root directory, then the Widget loader can just search for that and voila.

**Comment by Xerus2000** [comment]
As to displaying: Big icon with text below. Definitely. This is how most icons in the whole application work ;)

**Comment by sghpjuikit** [comment]
Disagree on Java widgets. I understand the reasoning, but it feels to me like I've already invested quite a lot in Java widgets. Compilation and stuff. If I can make them work with no problems I'd rather not discard the functionality. This has been bothering me a bit while porting code to Kotlin. I'm starting to remove Java creations that could be useful (like Utils), perhaps not for us anymore, but it seems like a bad idea to throw these things away.
I will consider your opinion. It does make sense from long term stand point. But the way Kotlin is - built on top of Java, not instead of, I think its better to not cut the pillars we stand on.

Agree on default icons.

Ok on layout. It's just the text is going to look a bit out of place I think. Will see. I'm porting Layouter/WidgetPicker to Kotlin right now so I may be able to experiment.

Disagree on icon files. I think you are considering external icons. I was considering icon font packs bundled with the application.
- It may be a little restraining, but it makes the application look tidy when everyone agrees on the icons and the design
- Raster graphics is absolute no go and loading vector graphics is hassle. The Glyph icons available are the best shot here. In many ways.

**Comment by Xerus2000** [comment]
> I'm starting to remove Java creations that could be useful (like Utils), perhaps not for us anymore, but it seems like a bad idea to throw these things away.

That's why we use git ;) also, if you deem something useful and reusable, create a utils library. That is how I solved that.

> Disagree on icon files. I think you are considering external icons. I was considering icon font packs bundled with the application.

Not quite sure on that, but I understand your point.

**Comment by sghpjuikit** [comment]
I'm still not sure how best to tackle this. It is relatively simple to implement icons, but I do not want to end up with a temporary solution. That's why this has been not done yet.

Though so far it seems to me like the font packs are a good starting point, and use these for common widgets. Later it could be extended into an svg support (JavaFX css allows this) or an image convention - however the image would break consistency of the skin - but that's how it is.

**Comment by sghpjuikit** [comment]
As for the Java based widgets - most of the have been ported to Kotlin by now or removed.

**Comment by sghpjuikit** [comment]
Implemented in  ab34144

However all widgets use the same icon for now. The customization is available, I have simply not decided on the particular icons
