### ISSUE TITLE
Release standalone util artefact

### ISSUE THREAD

**Issue by sghpjuikit** [sghpjuikit/player#171]
Licence: MIT or similar, something with short text.
Repository: not sure which one is good idea, something widespread?
JVM compile target: 12
name: sp.it.util
version: I'd like it to be locked with sp.it.pl (player), or at least major version, since util may need faster life-cycle

The module should stay as is, part of this project as that is its primary purpose and we really need the ability to refactor and accommodate the code.

Do I need to register domain or something?

Perhaps we could use github subprojects for this, but I'm not sure about making such changes.

**Comment by sghpjuikit** [comment]
@Xerus2000 can you help answering some of the concerns and give me some implementation pointers? I'll create PR with a review for this, so you will have a say about it, but I'd like some starting point.

**Comment by Xerus2000** [comment]
Have you had a look at how my util repo works? I don't create versions because I do breaking changes regularly anyways, instead I build the commit hash via jitpack.
If you want it to stay completely coupled to the player, a subproject could also be a good idea.
For licence: I use GPL for everything I personally care about and MIT for the projects that are basically just shared code, so yes, going with MIT sounds good.

**Comment by sghpjuikit** [comment]
Ok, I'll have a look.

**Comment by sghpjuikit** [comment]
While potentially useful, I'm closing this as out of scope of the project - there is no need for this. Can be reopened in the future.
