### ISSUE TITLE
Package names

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#18]
sp.it.pl is not a great package name - for example I always name my packages xerus.projectname
maybe something like sghpjuikit.playerfx, but does your current alias actually have a meaning?

I also often have xerus.util package, which collects utilities that don't directly belong to the project but are needed right now and may be outsourced to my utils project later if determined useful, I think it would make sense to do that here as well. That would also get rid of the multiple Files named "Util" all over the place.
Once gradle is embraced, building it with dependency on a separate Util project will be no problem.

**Comment by sghpjuikit** [comment]
I do not see a problem. Domain package structure is not required nor much needed, but because it does prevent namespace clutter I did refactor the packages (at your request). My nick does not mean anything and neither does the sp.it.pl, although it is supposed to be derived from "spit player", which comes from a nick originally derived from the nam of the WW2 fighter plane Spitfire.

I chose it so I can remember it and so it is very short, with each of the packages having exactly 2 characters (1 is too little and anything more would be annoying because some tools do not flatten the structure causing the need for unnecessary horizontal scrolling or stuff.

I do not like the idea of messing with packages much, because for git it means a change for every source file in the project. Again, I'm not sure it needs improving, but I'm open to arguments and suggestions, but so far you have not given me any reason.

As for the Utils, the unfortunate fact is that the Utils actually depend on the project and as such I'm not planning on taking it out of the project, because that would end up splitting it into external lib and project util, which is the last thing I desire - reducing code cohesion. The Util is also not in the state where I'd recommend other projects casually bringing it as dependency - Id suggest simply copy pasting what one needs.

I do believe it is a good idea to remove any Util -> Player dependencies, but it may be impossible without splitting, so I'd rather leave it as is.

That being said, I'll gladly hear more thoughts on this.

**Comment by sghpjuikit** [comment]
I''l note that if there's going to be package reorganization then
- the sooner the better
- it should be done all at once

**Comment by sghpjuikit** [comment]
sp.it.pl seems like an equivalent of xerus.music. Then there would be sp,it.util I guess. Once it can be separated.

Just a quick example from FontAwesome library: de.jensd.fx. Things like these are good enough I think.  I'm not worried, I simply do not wish for it to be longer than is absolutely necessary.

I've been trying to separate all of the Utils for a long time now, but its still not done. I would like to remove any connection there too. I'm also planning on then improving the documentation and complexity to make the utils more useful. In practice: documentation, better method names, all in Kotlin, extensions methods instead, etc.

**Comment by Xerus2000** [comment]
Let's leave the utils alone for now on thi

**Comment by Xerus2000** [comment]
Woops, misclick
Anyways, de.jensd is actually domain package: jensd is his alias, de the german url ending
fx already defines the project in question, but for here pl is pretty vacuous and I would prefer to simply call the package player - I don't see any downside to longer package names, it's not like you have to constantly type them out or something ^^

**Comment by Xerus2000** [comment]
I would honestly like if you simply acquired a general online alias and then we name the packages `alias.player`

**Comment by sghpjuikit** [comment]
As of now
player module: sp.it.pl
demo module: sp.it.demo
util module: sp.it.util

I think it is satisfactory. If there are no suggestions, I'll close this.
