### ISSUE TITLE
Fix Skins for Linux

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#22]
![image](https://user-images.githubusercontent.com/13354331/35273416-dfd63420-0038-11e8-8411-af08b6c68c59.png)
![image](https://user-images.githubusercontent.com/13354331/35273420-e34a376e-0038-11e8-8888-99daa09d59ad.png)

as is quite obvious, the css doesn't work properly on linux

**Comment by sghpjuikit** [comment]
This is a fairly annoying issue. The problem for me is I have no means of testing the solutions and as such can not effectively deal with the problem. I'll be thinking about possible causes. It may be the easiest for you to simply edit the Main.css yourself. Trying stuff like setting transparent bgr color for .pane .scrollpane and other unwilling components. It should work from the get go though, so the problem may be in how the skin was created (by editing the original Modena style), which makes it fairly outdated (and possibly broken). Quick fix may be easy, but proper solution could take a decent amount of effort.

**Comment by Xerus2000** [comment]
I appended this to the Flow.css file:
```
.popover-root > .bgr {
    -fx-fill: black;
}
```
and the background for the popovers indeed went black:
![image](https://user-images.githubusercontent.com/13354331/35416688-56d7355e-022a-11e8-9bab-aca17f33f5a9.png)

But there is another issue, whenever I "Open App actions" for the first time after launching the application, it's layed out like this:
![image](https://user-images.githubusercontent.com/13354331/35416714-71534ac6-022a-11e8-9622-00f761c338b1.png)
Reopening the widget then returns the layout to the usual state, which is also displayed above

**Comment by sghpjuikit** [comment]
Thank you for reporting about the partial solution.

 I can not investigate without Linux environment (which I'll be setting up hopefully soon), but the application of the skin must be somehow different, because on my end it is working properly. All I can provide for now is a tip to manually redeclare all broken skin parts from Main.css in Flow.css, or perhaps try with the Main.css itself. This may be an issue with css importing of transparent colors or background colors or css variables on Linux.

Some directions:
"-fx-background-color" or "-fx-fill" on elements like .scroll-pane .split-pane .table-view. These usually have color "transparent", which may be the problem. I would try using an rgb(0,0,0,0) or "none" or "null" value. Or redeclaring in the Flow skin. [guide](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html)

I apologize for the trouble.

PS: The Action popup layout is a known issue and i'ts on my todo list. It's another frustrating issue, but that's for another thread.

**Comment by Xerus2000** [comment]
I just realised the issue: Linux is case-sensitive, and your import to the main css file was like this `../main/main.css` while the directory and css file were capitalised! Everything works fine now, so I'm closing this. Watch case in the future, because case-sensitivity is a thing in other OS!

**Comment by sghpjuikit** [comment]
So it was importing issue after all! Glad you got it worked out.

About how this happened in the first place: Originally the skin file was called main.css, but I capitalized the name, but forgot to fix the import, because apparently Windows does not care.
