### ISSUE TITLE
Implement logarithmic volume adjustment

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#4]
float volume = 1 - (float)(Math.log(maxVolume - vol) / Math.log(maxVolume));

**Comment by sghpjuikit** [comment]
As per suggestion, implementing this in a upper abstraction layer (General player) seems like a reasonable thing to do. I'm thinking about the use of configuration of volume control between LINEAR, LOGARITHMIC, HYBRID, but there probably is not much, and until then logarithmic version will do a better job.

**Comment by sghpjuikit** [comment]
I'm having some trouble implementing this. 

The suggested formula does not work on normalized values (0-1), because if maxVolume == 1, then we get division by zero and in double an Infinity.

In normal values, we have to estimate maxVolume value (I read 60db is a good start) and denormalize the vol value. Is that correct?

It is also impossible to implement this on a GeneralPlayer layer, so the code must be duplicated, but it is only a single function call.

**Comment by Xerus2000** [comment]
Yeah I also found that issue in the formula and did not yet find a way to resolve it. My application currently has a maxVolume of 100.

> In normal values, we have to estimate maxVolume value (I read 60db is a good start) and denormalize the vol value. Is that correct?

Normal values don't really make much sense to me in this context?

These are the graphs of the two functions(scaled to 100)
![graph](https://user-images.githubusercontent.com/13354331/32731622-a1085a60-c88a-11e7-80bd-7fd283a5ed05.png)
btw I created these by entering this into Google: 1 - log(100-x)/log(100), (x/100)^2

As you can see, quadratic allows for finer control at higher volumes while logarithmic is better for lower volumes. Upon testing both, I found that quadratic is indeed nice on higher volumes, but has a significant drop in perceived volume when going down, while logarithmic is definetly linearly perceived.

I will send you a version of my player via Discord, which now works in terms of playing functionality, where you can swap between the formulas with the click of a checkbox.

**Comment by sghpjuikit** [comment]
I tested the volume slider in the test app, feels good to use, but its not 100% right either. In case of interest, here is some more material https://www.dr-lex.be/info-stuff/volumecontrols.html.

Because my backlog is pretty full as it is, I would welcome help, e.g., coming up with a set of useful (0,1) -> (0,1) functions and implementing them as an enum used as a playback setting, then making a pull request.

**Comment by sghpjuikit** [comment]
Using vlcj for playback solves this issue as vlcj or vlc seems to transform the values to log. JavaFX MediaPlayer will be used as a fallback if VLC is not found, in which case x^2 will be used unless someone comes up with a better solution that works. This is however a non issue, because VLC will most probably be packaged with the releases.
