### ISSUE TITLE
Provide a release

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#6]
Because only then can I ensure that I report relevant bugs to you

**Comment by sghpjuikit** [comment]
This is becoming a priority number one, but it goes hand in hand with standardizing the project and simplifying the build process for other developers. I'll need few days.

**Comment by sghpjuikit** [comment]
i think all major problems blocking this have been resolved. I have managed to decrease CPU usage, reduce memory usage (considerably), improve playback support & performance (using vlcj), simplify persistence (serialization instead of ObjectDB), remove numerous dependencies and clean up the project.

I'll do some improvements on UX for 1st-time users and update readme, after which I think an initial release can be made.

**Comment by sghpjuikit** [comment]
The release is now blocked by:
- few UX improvements (importing audio into library, action layout broken, guide, etc.)
- fixing critical bugs (mostly on Linux)
- setting up development process (readme, Gradle, etc)

**Comment by sghpjuikit** [comment]
I think we are nearing a release point. We have come a long way in the past year.

- Much work still needs to be done on UX, but it has been improved a lot.
- The only critical issue left I know of is VLC crashes. Perhaps also jNativehook.
- Gradle (+Kotlin DSL) was fully adopted, project set up has been dramatically simplified, we have CI and some other things.

Some of the problems I'd like to improve before release:
- improve READMEs and HOWTOs, this includes here on Github and those in the application
- improve branding (name, screenshots, etc.)
- hide/rework some of the more obscure functionalities (like docked window)
- tagging: this may be the most important - I want an option for read-only mode, perhaps avoidance of other application's tag data overwrite and better library

In the end, we will need to:
- polish the result
- decide on release form

**Comment by Xerus2000** [comment]
Release should be a zip for every OS (because we have a few OS-specific dependencies: OpenJFX, JDK, potentially vlc if you want to package it), simply as GitHub Release for now I'd think. The Windows zip then would also include the exe. We should set up a script that does all that packaging automatically on the CI, then it is easily repeatable.

**Comment by sghpjuikit** [comment]
OS-specific release
Ideally, there would be just one bundle that would handle all platforms. I'm aware of the fact that it is nonstandard, but personally I'd prefer it. The ability to transfer the application to different machine and use it is important.
I think it would be best to produce OS-specific and a multi-OS release. It may be unnecessary complication though, particularly, because  it would still be absolutely possible to merely transfer /user directory and continue using the application transparently

OS-specific dependencies
- Vlc will not be packaged with the app (as you already mentioned), but there may be an automatic download option, in similar vein to kotlinc. Ui reporting for missing vlc is yet to be implemented.
- JDK will be packaged along. This must be self-contained application. It is unclear to me what difference is there between JRE11 and JDK11, but I'm pretty positive JRE does not bunde javac. Note that we will bundle all java and javafx modules. We need to figure out if JRE11 is good enough (provided we bundle javac on our own).
- javac is fortunately part of JDK so this is bundled automatically
- kotlinc becomes more complicated. Current plan is for kotlinc management to be removed from build and added to the application itself, with user option for experimental kotlinc instead. Experimental kotlinc is much faster, but weights 200MB and with OS-specific binaries. See #136. Bundling kotlinc with the app would only be done for offline users, but I'd rather not bundle it at all.
- OpenJFX producing OS-specific binaries on build is something I was not expecting. It weights 35MB for one platform. All-OS release would be 70MB larger just for JavaFX.

Disk space
I checked biggest disk space consumers:
- /kotlinc: 40MB  // may not be bundled
- /lib: 50MB (this will grow significantly if all versions of javaFX are bundled at once)
- /vlc: 180MB  // will not be bundled
- /widgets: 12MB  // this includes their dependencies, the size is acceptable
- /user: 90MB  // not bundled, but user may expect around this much user data to be created
- /java: 280MB // JDK11 with non-stripped documentation files, JRE11 will be smaller

The bundle without vlc, user data and jdk weights 70MB

Licencing
The application needs a proper licence.

I think this project can not be open-sourced anymore, unless we split some parts off. Dual licencing is also on the table.

I also do not know how the licence applies differently to source code and binary.

We will also need to figure out JDK/JRE licences as well as kotlinc, vlc and so on and how they affect us. It may be necessary to put up a user agreement before the application is able to download these components.

**Comment by Xerus2000** [comment]
> OpenJFX producing OS-specific binaries on build is something I was not expecting. It weights 35MB for one platform. All-OS release would be 70MB larger just for JavaFX.

Not surprising. It was previously part of the JRE and that is OS-spcific as well ^^

> I think it would be best to produce OS-specific and a multi-OS release.

I'd agree with this. Once it sets up it isn't really an additional complication. Although you have to think how to swap JDKs and all that stuff. But the disk space itself should rarely be an issue in todays world, especially not if you use _this_ application ^^

> I think this project can not be open-sourced anymore, unless we split some parts off. Dual licencing is also on the table.

It is already open-sourced? Do you mean you'd not use something like MIT license?

**Comment by sghpjuikit** [comment]
I'd like to make an initial release within few weeks.

None of the issues on my radar are big. I'll do some testing if everything essential works as it should and prepare documentation/howtos.

**Comment by Xerus2000** [comment]
Continuing in #147 and #148
