### ISSUE TITLE
Fix window-resizing

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#7]
Add minimal values to prevent text from escaping to the outside. 
Investigate why it flickers while resizing and potential fixes.

**Comment by sghpjuikit** [comment]
There are two issues here:

1 The content flowing out of the popup windows if resized to small.

The problem here is more complex then it lets on - normally the popup resizes itself to fit the content, not vice versa, which raises question how the minimal size of the popup should be calculated (is it preferred or minimal size of the content?). Perhaps resizible popup means its content is resizable, which hints at the problem of user resizing the popup - where the content must accommodate instead. This requires a little figuring out to do and experimenting.

2 Flickering of the popup windows when resized.

This is caused by messy logic in the popup positioning, which aims to move the popup with its owner window. It is non trivial to fix this issue and it involves recoding the feature from scratch.

**Comment by sghpjuikit** [comment]
1 I set some of the popups to be non resizable (where it makes sense). But the problem remains.

2 I've been unable to figure out why the flickering occurs, it is there no matter what I do (I tried disabling almost all of the popup functions).

**Comment by sghpjuikit** [comment]
2 So the problem was using MouseEvent#getX() instead of #getScreenX() which led to odd behavior, because resizing the content shifted the values. Using absolute screen values instead of node-relative solved the problem.
